AllCops:
  NewCops: enable

Metrics/MethodLength:
  Max: 20

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
inherit_from: .rubocop-excludes.yml
