AllCops:
  NewCops: enable

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
inherit_from: .rubocop-excludes.yml
