AllCops:
  NewCops: enable

Metrics/MethodLength:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - spec/**/*
Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/AbcSize:
  Max: 35

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

inherit_from: .rubocop-excludes.yml
